
package com.proyectofinallasercom.Pantallas;


import java.time.LocalDate;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import dominio.Actividad;
import java.util.List;
import bo.ActividadBO;
import dao.ActividadDAO;
import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;

public class Estadisticas extends javax.swing.JFrame {
    LocalDate fInicial = LocalDate.MIN;
    LocalDate fFinal = LocalDate.MAX;
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    List<Actividad> lista;
    private final ActividadBO actividadBO;
    
    //regex
    Pattern pattern = Pattern.compile("^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$");
    Matcher matcher;
        
    
    public Estadisticas() {
        actividadBO = new ActividadBO(new ActividadDAO());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaInicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaFinal = new javax.swing.JTextField();
        btnComfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Estadisticas");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Fecha inicial");

        txtFechaInicial.setToolTipText("dd/mm/aaaa");
        txtFechaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicialActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Fecha Final");

        txtFechaFinal.setToolTipText("dd/mm/aaaa");

        btnComfirmar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnComfirmar.setText("Comfirmar");
        btnComfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComfirmarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Fecha Terminada", "Cliente", "Monto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Monto en periodo:");

        txtMonto.setEditable(false);

        btnSalir.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(400, 400, 400)
                        .addComponent(btnExportar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFechaInicial)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(btnComfirmar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addGap(63, 63, 63)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComfirmar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnExportar))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComfirmarActionPerformed
        // TODO add your handling code here:
        String fechaInicial = txtFechaInicial.getText();
        String fechaFinal = txtFechaFinal.getText();        
        
        // si la fecha inicial o final no estan llenadas, entonces no tiene limite
        
        // es decir, si se tiene la fecha inicial del 12/02/2024 y no tiene final
        // se va a mostrar cada tarea de ese dia y adelante
        
        // si no tiene inicial pero tiene una final de 12/02/2024
        // se muestra cada tarea antes de esa fecha
        
        // si las dos fechas estan vacias, se muestras todos los registros
        // o le avisamos al usuario que debe llenar una fecha
        // ustedes deciden.
        
        if (validacionFechas(fechaInicial, fechaFinal)){
            
            // SELECT * FROM Actividad
            // WHERE fechaRealTermino BETWEEN #fInicial# AND #fFinal#;
            
            
            try {
                // se obtiene la lista con todas las tareas
                lista = actividadBO.buscarActividadesEntreFechas(fInicial, fFinal);
                // se crea un contador de los montos
                BigDecimal monto = BigDecimal.ZERO;
                // limpia la tabla al momento de insertar datos nuevos
                modelo.setRowCount(0);
                
                // se crea el arreglo donde se va a guardar datos de cada actvidad
                String[] data = new String[4];
                for (Actividad act : lista) {
                    // se guarda los datos de la actividad en el arreglo
                    data[0] = act.getTitulo();
                    data[1] = act.getFechaRealTermino().toString();
                    data[2] = act.getCliente().getNombre();
                    data[3] = act.getMonto().toString();
                    
                    // se suma el monto
                    monto.add(act.getMonto());       
                    
                    // se agrega al model
                    modelo.addRow(data);
                }
                // se pone el model en la tabla
                jTable1.setModel(modelo);
                // se pone el monto acumulado en el periodo en el txt
                txtMonto.setText(monto.toString());
                
                // se agrega cada una de las tareas al modelo
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar actividades: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
        
        
    }//GEN-LAST:event_btnComfirmarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtFechaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicialActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }
    
    public boolean validacionFechas(String fechaInicial, String fechaFinal){
        if (!fechaInicial.trim().isEmpty()){
            matcher = pattern.matcher(fechaInicial);
            boolean matchFound = matcher.find();
            
            if(!matchFound) {                
                JOptionPane.showMessageDialog(this, "Por favor de insertar fecha valida (dd/mm/aaaa)", "Error", JOptionPane.ERROR_MESSAGE);
                return false;              
            }
            // se divide la fecha en partes en un arreglo
            String[] fechaInicialSplit = fechaInicial.split("/");
            
            // y se hace una fecha normal
            fInicial = LocalDate.of(Integer.parseInt(fechaInicialSplit[2]), Integer.parseInt(fechaInicialSplit[1]), Integer.parseInt(fechaInicialSplit[0]));
        } 
        // en el caso de que este vacio el campo, el valor inicial
        // es igual al valor minimo posible        
        else fInicial = LocalDate.MIN;
        
        if (!fechaFinal.trim().isEmpty()){
            matcher = pattern.matcher(fechaFinal);
            boolean matchFound = matcher.find();
            
            if(!matchFound) {                
                JOptionPane.showMessageDialog(this, "Por favor de insertar fecha valida (dd/mm/aaaa)", "Error", JOptionPane.ERROR_MESSAGE);
                return false;              
            }
            
            String[] fechaFinalSplit = fechaFinal.split("/");
            fFinal = LocalDate.of(Integer.parseInt(fechaFinalSplit[2]), Integer.parseInt(fechaFinalSplit[1]), Integer.parseInt(fechaFinalSplit[0]));
        } else fInicial = LocalDate.MAX;
        
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComfirmar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicial;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
